package config

import (
	"time"
)

// Login controls the lifetime of JWTs generated by the API login endpoint.
type Login struct {
	TokenTTL time.Duration
}

func (l Login) Validate() error {
	if l.TokenTTL < time.Second || l.TokenTTL > 24*time.Hour || l.TokenTTL%time.Second != 0 {
		return invalid("http.login.token_ttl", "must be whole seconds between 1s and 24h")
	}
	return nil
}
